all:
  vars:
    ansible_user: opc
    ansible_become: true
    ansible_host_key_checking: false
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    sub2api_deploy_dir: /home/opc/sub2api-deploy
    sub2api_compose_project_name: sub2api-deploy
    # DNF タスクで使用するシステム標準 Python
    dnf_python_interpreter: /usr/bin/python3
  children:
    awx_controller:
      hosts:
        instance-20251213-ARM_fw:
          ansible_host: 140.83.58.183
    sub2api_targets:
      hosts:
        amd-instance-internal1:
          ansible_host: 10.0.1.100
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=opc@140.83.58.183"
        amd-instance-internal2:
          ansible_host: 10.0.2.100
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=opc@140.83.58.183"
        arm-instance:
          ansible_host: 140.83.81.132
        amd-instance-1:
          ansible_host: 152.70.84.253
        amd-instance-2:
          ansible_host: 141.147.149.131
